FROM alpine

MAINTAINER eaptekar <eaptekar@student.unit.ua>

RUN apk update && \
	apk add busybox-extras

ENTRYPOINT telnet mtrek.com 1701

# docker build -t bonus02 .
# docker run -it --rm bonus02

-----------------------------

torbrowser
