FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]


#docker build -t ft-rails:on-build ft-rails
#git clone https://bitbucket.org/railstutorial/sample_app_4th_ed.git app
#docker build -t ex02 .
#docker run -it --rm -d -p 3000:3000 ex02 
#wait for some time...
#curl http://$(docker-machine ip Char):3000
